export const TILE_PIXEL_LENGTH = 32;
export const CHUNK_TILE_LENGTH = 16;
export const MAP_CHUNKS_WIDE = 32;
export const MAP_CHUNKS_HIGH = 32;

export const TILES_PER_CHUNK = CHUNK_TILE_LENGTH * CHUNK_TILE_LENGTH;
export const CHUNK_PIXEL_LENGTH = TILE_PIXEL_LENGTH * CHUNK_TILE_LENGTH;
export const MAP_TILES_WIDE = MAP_CHUNKS_WIDE * TILES_PER_CHUNK;
export const MAP_TILES_HIGH = MAP_CHUNKS_HIGH * TILES_PER_CHUNK;