export const TILE_PIXEL_LENGTH = 32;
export const CHUNK_TILE_LENGTH = 16;
export const TILES_PER_CHUNK = CHUNK_TILE_LENGTH * CHUNK_TILE_LENGTH;
export const CHUNK_PIXEL_LENGTH = TILE_PIXEL_LENGTH * CHUNK_TILE_LENGTH;